---
title: "The effect of climate change on disease burden"
author: "Katy Gaythorpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: 
- \usepackage{placeins}
output: 
  pdf_document:
    df_print: "kable"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
knitr::opts_chunk$set(
  fig.path = "ClimateChangeBurdenImagesNew/",
  dpi = 300
)

year_of_interest = 2050
```

```{r set_up}

library(maptools)
library(sp) 
library(shapefiles)
library(Hmisc)
library(fields)
library(dplyr)
library(EnvStats)
library(readr)
library(reshape)
library(abind)
library(mvtnorm)
library(RColorBrewer)
library(truncdist)
library(ggmcmc)
library(mcmcplots)
library(readr)
library(data.table)
library(ggplot2)


library(YFburden)
library(YFestimation)
library(snapalette)

#########################################################################################################
### SETTING THE WORKING DIRECTORY ###
#########################################################################################################

shpdir = paste0("../","shapefiles/gadm2/")

#########################################################################################################
### LOADING SHAPEFILES AND COUNTRIES ###
#########################################################################################################

#read shapefiles in
shp0 = readShapePoly(paste0(shpdir, "Africa_adm0.shp")) #if gadm2
shp1 = readShapePoly(paste0(shpdir, "Africa_adm1.shp"))

#adjust titles
shp1$adm0_adm1 = paste(shp1$ISO, shp1$ID_1, sep="_")
shp1 = shp1[order(shp1$adm0_adm1),]

#read countries in
Countries = read_csv(paste0("../Data/","Countries.csv"))
c34 = Countries$c34
country34 = Countries$country34

#########################################################################################################
### SOURCE FUNCTIONS ###
#########################################################################################################

R.utils::sourceDirectory("FUNCTIONS", modifiedOnly = FALSE)
#########################################################################################################
### LOAD ENVIRONMENTAL DATA ###
#########################################################################################################

Env_Table_path = (paste0("../Data/","Environment/Africa_adm1_dat_2017.csv")) #this file is adapted by hand to have latest outbreaks

dat_full = read.csv(Env_Table_path, stringsAsFactors=FALSE)

envdat = launch_env_dat(filepath = NA, dat_full = dat_full, c34 = c34) 
```
# Introduction

The purpose of this markdown is to take the predicted force of infection estimates calculated in "Full_projections" and turn them into predictions of the burden in `r toString(year_of_interest)`.

We begin by comparing the force of infection predictions.

# Comparing the force of infection

```{r import predictions and plot}


Foi_samples = read.csv("Foi_climate_samples_20180830.csv", stringsAsFactors = FALSE)

Foi_median_samples= read.csv("Foi_median_climate_samples_20180830.csv", stringsAsFactors = FALSE)

Foi_samples_all = melt(Foi_samples, id = "scenario")

Foi_samples_all$scenario = as.factor(Foi_samples_all$scenario)

ggplot(Foi_samples_all) + geom_boxplot( aes(x = scenario, y = value, colour = scenario))
```

```{r compare_transmission}

par(mfrow=c(1,2))

#get median values
Foi_runs = filter(Foi_median_samples, scenario == 0)
Foi_runs_add2 = filter(Foi_median_samples, scenario == 2)
Foi_runs_add4 = filter(Foi_median_samples, scenario == 4)

#calculate difference
difference_add2 = (Foi_runs_add2[,-1] - Foi_runs[,-1])/Foi_runs[,-1] *100
difference_add4 = (Foi_runs_add4[,-1] - Foi_runs[,-1])/Foi_runs[,-1] *100


mybreaks= seq(-150,150, length.out=100)
mycols =  snapalette("Camden",length(mybreaks)-1, type = "continuous")
mm = match(shp1$adm0_adm1,envdat$dat$adm0_adm1)
vcols = findInterval(difference_add2,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30), main= "% difference +2")
mm0 = match(shp0$ISO,c34) #
plot(shp0[is.na(mm0),],col="grey70",add=T) 
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=T)

image.plot(legend.only=TRUE,breaks=mybreaks,col=mycols,zlim=c(0,1), horizontal = TRUE, 
           #axis.args = list(at = c(-3:1), labels =c( "0.001", "0.01", "0.1","1","10"), las =2),
           legend.mar = 3.5)
#############################################################################################



vcols = findInterval(difference_add4,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30), main= "% difference +4")
mm0 = match(shp0$ISO,c34) #
plot(shp0[is.na(mm0),],col="grey70",add=T) 
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=T)

image.plot(legend.only=TRUE,breaks=mybreaks,col=mycols,zlim=c(0,1), horizontal = TRUE, 
           #axis.args = list(at = c(-3:1), labels =c( "0.001", "0.01", "0.1","1","10"), las =2),
           legend.mar = 3.5)

  
```


```{r compare_transmission_all}

par(mfrow=c(1,2))

#get median values
Foi_runs = apply(filter(Foi_samples, scenario == 0), 2, median)
Foi_runs_add2 = apply(filter(Foi_samples, scenario == 2), 2, median)
Foi_runs_add4 = apply(filter(Foi_samples, scenario == 4), 2, median)

#calculate difference
difference_add2 = (Foi_runs_add2[-1] - Foi_runs[-1])/Foi_runs[-1] *100
difference_add4 = (Foi_runs_add4[-1] - Foi_runs[-1])/Foi_runs[-1] *100


mybreaks= seq(-150,150, length.out=100)
mycols = snapalette("Bouquet",length(mybreaks)-1, type = "continuous")
mm = match(shp1$adm0_adm1,envdat$dat$adm0_adm1)
vcols = findInterval(difference_add2,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30), main= "% difference +2")
mm0 = match(shp0$ISO,c34) #
plot(shp0[is.na(mm0),],col="grey70",add=T) 
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=T)

image.plot(legend.only=TRUE,breaks=mybreaks,col=mycols,zlim=c(0,1), horizontal = TRUE, 
           #axis.args = list(at = c(-3:1), labels =c( "0.001", "0.01", "0.1","1","10"), las =2),
           legend.mar = 3.5)
#############################################################################################



vcols = findInterval(difference_add4,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30), main= "% difference +4")
mm0 = match(shp0$ISO,c34) #
plot(shp0[is.na(mm0),],col="grey70",add=T) 
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=T)

image.plot(legend.only=TRUE,breaks=mybreaks,col=mycols,zlim=c(0,1), horizontal = TRUE, 
           #axis.args = list(at = c(-3:1), labels =c( "0.001", "0.01", "0.1","1","10"), las =2),
           legend.mar = 3.5)

  
```

#Burden predictions

```{r burden}


#import coverage data for each scenario
coverage_df_prev = read.csv(paste0("../Data/Vaccination/Outputs/", 
                                   "vaccination_coverage_country_year_", 
                                   "preventive", ".csv"), 
                            stringsAsFactors = FALSE)

####

pop_all = read.csv("../Data/Population/201708/201710gavi-5_dds-201710_int_pop_both.csv", 
                   stringsAsFactors = FALSE)

## Patch it up with GAB and GNQ data
pop_patch_GAB_GNQ = read.csv("../Data/Population/201708/201710gavi-5_dds-201710_int_pop_both_GAB_GNQ.csv", 
                             stringsAsFactors = FALSE)

pop_all = rbind(pop_all, pop_patch_GAB_GNQ)

pop_all = filter(pop_all, year>1939)

scenarios = c(0,2,4)
##########################################

vac_eff = 0.975

n_samples = 10

infections =  rep(NA, nrow(Foi_samples)*35)
dim(infections) = c(nrow(Foi_samples), 35)

param_country_vec = NULL

for (country_ind in 1: 34){
  
  
  #get coverage for that country
  coverage_country_prev = filter(coverage_df_prev, country_code == c34[country_ind])
  
  #population for that country
  pop_country = filter(pop_all, country_code == c34[country_ind])
  
  ### want to reshape into previous format ###
  pop_new = NULL
  for (y in max(pop_country$year) : min(pop_country$year)){
    tmp = c(y, filter(pop_country, year == y)$value)
    
    if(length(tmp)< 102) {tmp = c(tmp, rep(NA, 102-length(tmp)))}
    pop_new = rbind(pop_new, tmp)
  }
  colnames(pop_new) = c("year", 0:100)
  pop_new = pop_new[order(pop_new[,1]),]
  ############################################
  
  #get model type
  model_type = "Foi"
  
  for( index in 1:n_samples){#(nrow(Foi_samples)/3)){
    for (s in 1:3){
      
      Foi_samples_scenario = filter(Foi_samples, scenario == scenarios[s])
      Foi_samples_baseline = filter(Foi_samples, scenario == 0)
    
    param = Foi_samples_scenario[index,2:480]
    param_base = Foi_samples_baseline[index, 2:480]
    
    #collect transmission param for that country
    param_country = param[ grep(c34[country_ind], names(param)) ]
    param_country_base = param_base[ grep(c34[country_ind], names(param_base)) ]
    
    #average over country
    param_country_ave = mean( as.numeric(param_country) )
    param_country_ave_base = mean( as.numeric(param_country_base) )
    
    year_end = year_of_interest
    
    #calculate start conditions with baseline
    immunity_start = fun_immunityStart(model_type,
                                       transmission_param = param_country_ave_base,
                                       age_max = 100,
                                       pop = pop_new,
                                       old_coverage = coverage_country_prev)


    #calculate burden in year of interest
    
    out_prev = run_infections_unit(model_type,
                                   transmission_param = param_country_ave,
                                   vac_eff,
                                   years = year_end,
                                   age_max = 100,
                                   pop = pop_new,
                                   coverage = coverage_country_prev,      #this is a subset of pop_moments_whole for adm1s of interest
                                   immunity_start)
    
    
    infections[index + nrow(Foi_samples_baseline)* (s-1)  , c(country_ind, 35)] = c(sum(out_prev$new_infections) , scenarios[s])
    
    param_country_vec = rbind(param_country_vec , c(param_country_ave, model_type, c34[country_ind]))
    }
  } 
}

infections_df = as.data.frame(infections) 
names(infections_df)[1:34]  = c34

names(infections_df)[ncol(infections_df)] = "scenario"


write.csv(infections_df, paste0("infections_df_", format(Sys.time(),"%Y%m%d"), ".csv"), row.names = FALSE)
```


```{r burden_plot}

P_severe =  rbeta(1000,6.367309,44.60736) 

burden_df = melt(infections_df, id = "scenario")
burden_df$value = burden_df$value * P_severe

colours = snapalette("Barcelona", 5, type = "discrete")[c(2,4,5)]

ggplot(burden_df, aes(x = variable, y = value, fill = as.factor(scenario))) + 
  geom_col(  position = position_dodge()) + 
  theme( axis.text.x = element_text(angle = 90, hjust = 1)) + 
  scale_fill_manual(values = colours)+
  xlab("") + ylab("Burden") + labs(fill = "Scenario")


```



```{r rank_change}

df_value_change = data.frame("country" = as.character(filter(burden_df, scenario==0)$variable),
                             "baseline" = filter(burden_df, scenario == 0)$value,
                             "warming_2" = filter(burden_df, scenario == 2)$value,
                             "warming_4" = filter(burden_df, scenario == 4)$value)


WestAfrica = c("SEN", "GMB", "MRT", "MLI", "BFA", "SLE", "NGA", "NER", "BEN", "TGO", "GHA", "CIV", "LBR", "GIN", "GNB")

df_value_change$we = ifelse(df_value_change$country %in% WestAfrica, "W", "E")

df_vale_we = data.frame("Location" = c("West", "East and central"),
                        "baseline" = c(sum(filter(df_value_change, we=="W")$baseline), sum(filter(df_value_change, we=="E")$baseline,na.rm=TRUE) ),
                        "warming_2" = c(sum(filter(df_value_change, we=="W")$warming_2), sum(filter(df_value_change, we=="E")$warming_2,na.rm=TRUE) ),
                        "warming_4" = c(sum(filter(df_value_change, we=="W")$warming_4), sum(filter(df_value_change, we=="E")$warming_4,na.rm=TRUE) ))


ggplot(df_vale_we) + geom_segment( aes( x = as.factor(1), y = log10(baseline), xend = as.factor(2), yend = log10(warming_2), colour = Location), size = 1) +
                     geom_segment( aes( x = as.factor(2), y = log10(warming_2), xend = as.factor(3), yend = log10(warming_4), colour = Location), size =1) +
  scale_colour_manual( values = c("blue", "orange")) +
  labs(x = "", y = "Burden (log scale)") + 
  scale_x_discrete(breaks = c("1","2","3"),labels=c( "Baseline", "Warming +2", "Warming +4"))

```

```{r rank_change_uncert}

df_melted_we = melt(df_value_change[,2:5], id = "we")

df_melted_we$we = factor(df_melted_we$we, levels = c("W", "E") )

ggplot(df_melted_we) + 
  geom_violin( aes(x = variable, y = log10(value),  fill = we), draw_quantiles = 0.5) + 
  scale_fill_manual(values = colours[2:1]) + 
  xlab("Scenario") + 
  ylab("Burden (log scale)") + 
  labs(fill = "Area") 

```