---
title: "Plot data"
author: "Katy Gaythorpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: 
- \usepackage{placeins}
output: 
  pdf_document:
    df_print: "kable"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE)
knitr::opts_chunk$set(
  fig.path = paste0("DataImages", "/"),
  dpi = 300,
  dev = c('png')
)
```

# Occurrence data

```{r set_up}

library(maptools)
library(sp) 
library(shapefiles)
library(Hmisc)
library(fields)
library(dplyr)
library(EnvStats)
library(readr)
library(reshape)
library(truncdist)
library(RColorBrewer)

library(ggmcmc)
library(mcmcplots)
library(R.utils)

library(YFestimation)
library(snapalette)
library(KsetupR)

#########################################################################################################
### SETTING THE WORKING DIRECTORY ###
#########################################################################################################

shpdir = paste0("../","shapefiles/gadm2/")

#########################################################################################################
### LOADING SHAPEFILES AND COUNTRIES ###
#########################################################################################################

#read shapefiles in
shp0 = readShapePoly(paste0(shpdir, "Africa_adm0.shp")) #if gadm2
shp1 = readShapePoly(paste0(shpdir, "Africa_adm1.shp"))

#adjust titles
shp1$adm0_adm1 = paste(shp1$ISO, shp1$ID_1, sep="_")
shp1 = shp1[order(shp1$adm0_adm1),]

#read countries in
Countries = read_csv(paste0("../Data/","Countries.csv"))
c34 = Countries$c34
country34 = Countries$country34


```

```{r occurrence, fig.cap="Location of YF occurrence from 1984 to 2018. Red indicates occurrence, white no reports and black indicates that area is not in the YF endemic region."}
Env_Table_path = paste0("../Data/","Environment/dat_worldclim_all_2019-04-15.csv") 
dat_full = read.csv(Env_Table_path, stringsAsFactors=FALSE)

### data ###
par(mar = 0*c(5.1,4.1,4.1,2.1))

plot(shp0, col = "grey90", xlim=c(-15,45), ylim=c(-20,35))
mm0 = match(shp0$ISO,c34) #
plot(shp0[is.na(mm0),],col="black",add=T)

pres= dat_full$adm0_adm1[dat_full$cas.or.out>0]
mm1<-match(pres, shp1$adm0_adm1)

plot(shp1[mm1,], col="red", border = "red",  add=TRUE)
plot(shp0,lwd=2, add=TRUE)


```

# Worldclim mid 

```{r worldclim, fig.cap="worldclim_temp_mid. Black indicates that area is not in the YF endemic region at baseline."}

par(mar = 0*c(5.1,4.1,4.1,2.1))

dat_full = dat_full %>% mutate(worldclim_temp_mid = (dat_full$X1970_1990tnnow + dat_full$X1970_1990txnow)/2)
  
dat_full = dat_full %>% mutate(worldclim_temp_range = (dat_full$X1970_1990txnow - dat_full$X1970_1990tnnow))

mybreaks= seq(min(dat_full$worldclim_temp_mid)-0.1, max(dat_full$worldclim_temp_mid)+0.1, length.out=100)
mycols =   colorRampPalette(brewer.pal(9, "Oranges") )(length(mybreaks)-1)
mm = match(shp1$adm0_adm1, dat_full$adm0_adm1)
vcols = findInterval(dat_full$worldclim_temp_mid,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
mm0 = match(shp0$ISO,c34) #
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=TRUE)
plot(shp0[is.na(mm0),],col="black",add=T) 

image.plot(legend.only=TRUE,
           breaks=mybreaks,
           col=mycols,
           zlim=c(0,1), 
           horizontal = FALSE)

```

```{r worldclim_scenario, fig.cap="worldclim_temp_mid_scenario. Black indicates that area is not in the YF endemic region."}

source('Z:/YF_climateChange/FUNCTIONS/clim_change_fun.R')

par(mar = 0*c(5.1,4.1,4.1,2.1))

for(s in c(26,45,60,85)){
  for(y in c(2050, 2070)){
    
    dat = prepare_climate_dat(dat_full, scenario = s, year = y)
    
    temp_change = dat$worldclim_temp_mid - (dat_full$X1970_1990tnnow + dat_full$X1970_1990txnow)/2
    
    print(min(temp_change))
    print(max(temp_change))
    
    mybreaks = seq(-0.1, 5, length.out=100)

    mycols =   colorRampPalette(brewer.pal(9, "Oranges") )(length(mybreaks)-1)
    mm = match(shp1$adm0_adm1, dat$adm0_adm1)
    vcols = findInterval(temp_change,mybreaks)
    
    plot(shp0, xlim=c(-15,45),ylim=c(-20,30), main = paste0("Year ", y, ", scenario ", s))
    mm0 = match(shp0$ISO,c34) #
    plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
    plot(shp0, lwd=2, add=TRUE)
    plot(shp0[is.na(mm0),],col="black",add=T) 
    
    image.plot(legend.only=TRUE,
               breaks=mybreaks,
               col=mycols,
               zlim=c(0,1), 
               horizontal = FALSE)
  }
}

```

# Worldclim range

```{r worldclim_range, fig.cap="worldclim_temp_range. Black indicates that area is not in the YF endemic region."}

par(mar = 0*c(5.1,4.1,4.1,2.1))


mybreaks= seq(min(dat_full$worldclim_temp_range)-0.1, max(dat_full$worldclim_temp_range)+0.1, length.out=100)
mycols =   snapalette("Bouquet", n = length(mybreaks)-1, type = "continuous")
mm = match(shp1$adm0_adm1, dat_full$adm0_adm1)
vcols = findInterval(dat_full$worldclim_temp_range,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
mm0 = match(shp0$ISO,c34) #
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=TRUE)
plot(shp0[is.na(mm0),],col="black",add=T) 

image.plot(legend.only=TRUE,
           breaks=mybreaks,
           col=mycols,
           zlim=c(0,1), 
           horizontal = FALSE)

```

```{r worldclim_range_scenario, fig.cap="worldclim_temp_range_scenario. Black indicates that area is not in the YF endemic region."}


par(mar = 0*c(5.1,4.1,4.1,2.1))

for(s in c(26,45,60,85)){
  for(y in c(2050, 2070)){
    
    dat = prepare_climate_dat(dat_full, scenario = s, year = y)
    
    wr = dat$worldclim_temp_range - (dat_full$X1970_1990txnow - dat_full$X1970_1990tnnow)
    
    mybreaks= seq(-5, 5, length.out=100)
    mycols =   snapalette("Bouquet", n = length(mybreaks)-1, type = "continuous")
    mm = match(shp1$adm0_adm1, dat$adm0_adm1)
    vcols = findInterval(wr,mybreaks)
    
    plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
    mm0 = match(shp0$ISO,c34) #
    plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
    plot(shp0, lwd=2, add=TRUE)
    plot(shp0[is.na(mm0),],col="black",add=T) 
    
    image.plot(legend.only=TRUE,
               breaks=mybreaks,
               col=mycols,
               zlim=c(0,1), 
               horizontal = FALSE)
  }
}

```

# Rainfall mean

```{r RFE, fig.cap="RFE mean. Black indicates that area is not in the YF endemic region."}

par(mar = 0*c(5.1,4.1,4.1,2.1))

mybreaks= seq(min(dat_full$X1970_1990prnow)-0.1, max(dat_full$X1970_1990prnow)+0.1, length.out=100)
mycols =   rev( snapalette("Venice", type = "continuous", length(mybreaks)-1))
mm = match(shp1$adm0_adm1, dat_full$adm0_adm1)
vcols = findInterval(dat_full$X1970_1990prnow,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
mm0 = match(shp0$ISO,c34) #
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=TRUE)
plot(shp0[is.na(mm0),],col="black",add=T) 

image.plot(legend.only=TRUE,
           breaks=mybreaks,
           col=mycols,
           zlim=c(0,1), 
           horizontal = FALSE)

```


```{r RFE_scenario, fig.cap="RFE scenario. Black indicates that area is not in the YF endemic region."}


par(mar = 0*c(5.1,4.1,4.1,2.1))

for(s in c(26,45,60,85)){
  for(y in c(2050, 2070)){
    
    dat = prepare_climate_dat(dat_full, scenario = s, year = y)
    
    rfe_diff = dat$worldclim_rainfall - dat_full$X1970_1990prnow
    
    mybreaks= seq(-50, 50, length.out=100)
    mycols =   rev( snapalette("Venice", type = "continuous", length(mybreaks)-1)) 
    
    mm = match(shp1$adm0_adm1, dat$adm0_adm1)
    vcols = findInterval(rfe_diff,mybreaks)
    
    plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
    mm0 = match(shp0$ISO,c34) #
    plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
    plot(shp0, lwd=2, add=TRUE)
    plot(shp0[is.na(mm0),],col="black",add=T) 
    
    image.plot(legend.only=TRUE,
               breaks=mybreaks,
               col=mycols,
               zlim=c(0,1), 
               horizontal = FALSE)
  }
}

```



# log.surv.qual.adm0

```{r surv.qual.adm0, fig.cap="log.surv.qual.adm0. Black indicates that area is not in the YF endemic region."}

par(mar = 0*c(5.1,4.1,4.1,2.1))

mybreaks= seq(min(dat_full$surv.qual.adm0, na.rm = TRUE)-0.1, max(dat_full$surv.qual.adm0, na.rm = TRUE)+0.1, length.out=100)
mycols =   colorRampPalette(brewer.pal(9, "Purples") )(length(mybreaks)-1)
mm = match(shp1$adm0_adm1, dat_full$adm0_adm1)
vcols = findInterval(dat_full$surv.qual.adm0,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
mm0 = match(shp0$ISO,c34) #
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=TRUE)
plot(shp0[is.na(mm0),],col="black",add=T) 

image.plot(legend.only=TRUE,
           breaks=mybreaks,
           col=mycols,
           zlim=c(0,1), 
           horizontal = FALSE)

```

# lon

```{r lon, fig.cap="lon. Black indicates that area is not in the YF endemic region."}

par(mar = 0*c(5.1,4.1,4.1,2.1))

mybreaks= seq(min(dat_full$lon)-0.1, max(dat_full$lon)+0.1, length.out=100)
mycols =   colorRampPalette(brewer.pal(9, "Spectral") )(length(mybreaks)-1)
mm = match(shp1$adm0_adm1, dat_full$adm0_adm1)
vcols = findInterval(dat_full$lon,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
mm0 = match(shp0$ISO,c34) #
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=TRUE)
plot(shp0[is.na(mm0),],col="black",add=T) 

image.plot(legend.only=TRUE,
           breaks=mybreaks,
           col=mycols,
           zlim=c(0,1), 
           horizontal = FALSE)

```

# logpop

```{r logpop, fig.cap="logpop. Black indicates that area is not in the YF endemic region."}

par(mar = 0*c(5.1,4.1,4.1,2.1))

mybreaks= seq(min(dat_full$logpop)-0.1, max(dat_full$logpop)+0.1, length.out=100)
mycols =   colorRampPalette(brewer.pal(9, "Greens") )(length(mybreaks)-1)
mm = match(shp1$adm0_adm1, dat_full$adm0_adm1)
vcols = findInterval(dat_full$logpop,mybreaks)

plot(shp0, xlim=c(-15,45),ylim=c(-20,30))
mm0 = match(shp0$ISO,c34) #
plot(shp1[!is.na(mm),],col=mycols[vcols], xlim=c(-15,45),ylim=c(-20,30) , lty=0, add=T)
plot(shp0, lwd=2, add=TRUE)
plot(shp0[is.na(mm0),],col="black",add=T) 

image.plot(legend.only=TRUE,
           breaks=mybreaks,
           col=mycols,
           zlim=c(0,1), 
           horizontal = FALSE)

```