---
title: "Uncertain projections"
author: "Katy Gaythorpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: 
- \usepackage{placeins}
output: 
  pdf_document:
    df_print: "kable"
params:
  save_samples: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
knitr::opts_chunk$set(
  fig.path = paste0("Uncertain_projections_", Sys.Date(), "/"),
  dpi = 300,
  dev = c('png')
)
```

```{r set_up}

library(maptools)
library(sp) 
library(shapefiles)
library(Hmisc)
library(fields)
library(dplyr)
library(tibble)
library(tidyr)
library(magrittr)
library(readr)
library(purrr)
library(ggridges)
library(boot)

library(ggmcmc)
library(mcmcplots)
library(R.utils)

library(YFestimation)
library(snapalette)
library(KsetupR)

#########################################################################################################
### SETTING THE WORKING DIRECTORY ###
#########################################################################################################

shpdir = paste0("../","shapefiles/gadm2/")

#########################################################################################################
### LOADING SHAPEFILES AND COUNTRIES ###
#########################################################################################################

#read shapefiles in
shp0 = readShapePoly(paste0(shpdir, "Africa_adm0.shp")) #if gadm2
shp1 = readShapePoly(paste0(shpdir, "Africa_adm1.shp"))

#adjust titles
shp1$adm0_adm1 = paste(shp1$ISO, shp1$ID_1, sep="_")
shp1 = shp1[order(shp1$adm0_adm1),]

#read countries in
Countries = read_csv(paste0("../Data/","Countries.csv"))
c34 = Countries$c34
country34 = Countries$country34

#########################################################################################################
### SOURCE FUNCTIONS ###
#########################################################################################################

sourceDirectory("FUNCTIONS", modifiedOnly = FALSE)


snapal = "Stavanger"

```

# Visualising transmission intensity

## Direct values

```{r load_transmission}

transmission_proj = read.csv( "transmission_intensity_samples.csv", stringsAsFactors = FALSE)

transmission_proj %<>% mutate(year = as.character(year), scenario = as.character(scenario))  %>% 
                       mutate(year = factor(year, levels = c("now", 2050, 2070)))

tp = transmission_proj %>% filter( !(scenario %in% c(45, 60, 85) & year == "now"))
tp$scenario[tp$year == "now"] = "now"

```

```{r transmission_by_country, fig.height = 10, fig.width = 10}
ggplot(tp) + 
  geom_violin(aes(fill = scenario, y = FOI, x = year), position="dodge", draw_quantiles = 0.5) + 
  facet_wrap(adm0~.) +
  scale_fill_manual(values = c(c(snapalette(snapal)[1:4], "white")[1:4], "white") ) +
  theme_bw() +
  ylab("Force of infection")+
  scale_y_log10()

```



```{r transmission_by_area_calc}

west = c("BEN", "BFA", "GMB", "GHA", "GIN", "GNB", "CIV", "LBR", "MLI", "MRT", "NER", "NGA", "SEN", "SLE", "TGO")

central = c("TCD", "CAF", "CMR", "GAB", "COD", "COG", "AGO", "SSD", "SDN")

tp %<>% mutate(WE = ifelse(adm0 %in% west, "West", 
                               ifelse(adm0 %in% central, "Central and Sudan",
                                      "East")))

```



```{r transmission_by_area2}
ggplot(tp, aes(x = FOI, y =  year, fill = scenario)) + 
  geom_density_ridges(alpha = 0.5 , scale = 1) +
  theme_ridges() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white")) +
  scale_x_log10()+
  scale_y_discrete(expand = c(0.01, 0)) +
  xlab("Force of infection")+
  facet_wrap(~WE) 

```


```{r transmission_country2, fig.height=12, fig.width=10, fig.cap="Transmission per country."}

tmp = tp
tmp = bind_rows(tmp, 
                filter(tmp, scenario == "now") %>% mutate(year = "2050"),
                filter(tmp, scenario == "now") %>% mutate(year = "2070") )

g=ggplot( filter(tmp, year %in% c(2050, 2070) )) + 
  geom_density_ridges(scale = 3, 
                      alpha = 0.5,
                      aes(x = FOI, y = adm0, fill = scenario)) + 
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  theme_ridges()+
  xlab("Force of infection") + 
  ylab("Country")+
  xlim(-100, 500) +
  scale_y_discrete(expand = c(0.01, 0)) +
  facet_wrap(year~., nrow = 1)+
  scale_x_log10()+
  theme(text = element_text(size = 20))

rm(tmp)
print(g)

```

  
## Relative difference

```{r calc_diff}
tmp = filter(transmission_proj, year == "now") 
tmp$scenario = "now"
tmp %<>% dplyr::rename(FOI_now = FOI) %>% select("adm0", "FOI_now", "sample")

transmission_proj %<>% left_join( tmp, by = c("adm0", "sample"))
transmission_proj = unique(transmission_proj)

transmission_proj %<>% mutate(percent_diff = ((FOI - FOI_now)/FOI_now)*100)


```



```{r difference_by_country2, fig.width=10, fig.height=12}
scen_vec = c(26, 45, 60, 85)

for(s in 1:4){
  for(y in c(2050, 2070)){
    
    col = snapalette(snapal)[s]
    
    g = ggplot( filter( transmission_proj, year %in% y & scenario %in% scen_vec[s] )) + 
      geom_density_ridges(scale = 3, aes(x = percent_diff, y = reorder(adm0, percent_diff) ), 
                          fill = col,
                          alpha = 0.5) + 
      theme_ridges()+
      xlab("Change in force of infection (%)") + 
      ylab("Country")+
      #labs(title = paste0("Year ", y, ", scenario ", s))+
      scale_y_discrete(expand = c(0.01, 0)) +
      geom_hline(yintercept = 0, color = snapalette(snapal)[5])+
      xlim(-100, 300) +
      geom_vline(xintercept = 0)+
      guides(fill = FALSE)+
      theme(text = element_text(size = 30))
    
    print(g)
    
  }
}

```


```{r difference_by_area_calc}

transmission_proj %<>% mutate(WE = ifelse(adm0 %in% west, "West", 
                               ifelse(adm0 %in% central, "Central and Sudan",
                                      "East")))
```




```{r difference_by_area3, fig.width=10, fig.height=8}


ggplot( filter( transmission_proj, year %in% c(2050, 2070) )) + 
  geom_density_ridges(scale = 0.9, 
                      aes(x = percent_diff, y = WE, fill = scenario, alpha = year)) + 
  facet_wrap(~scenario) +
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  scale_alpha_manual(values = c(0.1,0.8))+
  theme_ridges()+
  xlab("Change in force of infection (%)") + 
  ylab("")+
  scale_y_discrete(expand = c(0.01, 0)) +
  geom_hline(yintercept = 0, color = snapalette(snapal)[5])+
  xlim(-100, 500) +
  geom_vline(xintercept = 0)+
  guides(fill = FALSE)

#rm(transmission_proj, tmp, tp)

```

```{r transmission_difference_table}

p <- c(0.025, 0.25, 0.5, 0.75, 0.975)

p_names <- map_chr(p, ~paste0(.x*100, "%"))

p_funs <- map(p, ~partial(quantile, probs = .x, na.rm = TRUE)) %>% 
  set_names(nm = p_names)


out_df = transmission_proj %>% 
  group_by( year, scenario) %>% 
  summarise_at(vars(percent_diff), funs(!!!p_funs)) %>% 
  filter(year %in% c( 2050, 2070))

write.csv(out_df, "table_of_change_foi.csv", row.names = FALSE)

kableExtra::kable(out_df, caption = "FOI change per year in each scenario")

```

```{r transmission_difference_country_table}

scen_vec = c(26, 45, 60, 85)

for(s in 1:4){
  for(y in c(2050, 2070)){
    
    out_df = transmission_proj %>% 
      group_by( year, scenario, adm0) %>% 
      summarise_at(vars(percent_diff), funs(!!!p_funs)) %>% 
      filter(year %in% y & scenario == scen_vec[s]) %>%
      arrange(year, scenario, `50%`)
    
    write.csv(out_df, paste0("table_of_change_foi_country_", y, "_", scen_vec[s],".csv"), row.names = FALSE)
    
    kableExtra::kable(out_df, caption = paste0("Change in FOI in ", y, "in scenario", scen_vec[s]))
    
    
  }
}

```


# Visualising burden

```{r load_burden}

#get files in infections directory
fil = list.files("infections2")

inf_df = NULL
for(i in 1:length(fil)){
  inf_df[[i]] = mutate_all( read.csv(paste0("infections2/", fil[i]), stringsAsFactors = FALSE), as.character)
}

inf_df = bind_rows(inf_df)

inf_df = gather(inf_df,   "Year", "Infections", -c(adm0, scenario, sample))

inf_df$Year = gsub("X", "", inf_df$Year)

inf_df %<>% mutate( Year = as.character(Year), Infections = as.numeric(Infections)) %>% filter(Year %in% c(2018, 2050, 2070))



```


```{r infections, fig.cap="Infections."}

ggplot(inf_df,
       aes(x = Year, y = Infections, fill = scenario)) +
  geom_violin( position="dodge", draw_quantiles = 0.5) +
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_y_log10()

```

```{r infections_scenario_country, fig.cap="Infections.", fig.height = 12, fig.width = 10}
ggplot(inf_df,
       aes(x = Year, y = Infections, fill = scenario)) + 
  geom_violin( position="dodge", draw_quantiles = 0.5) + 
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  facet_wrap(~adm0, scales = "free_y")+
  scale_y_log10()

```



\FloatBarrier

# Cases and Deaths

```{r get_burden}

n_samples = length(unique(inf_df$sample))

P_severe_runs = rbeta(n_samples, 6.367309,44.60736)
P_death_runs = rbeta(n_samples, 16.43466, 18.49048)

tmp_df = data.frame(sample = unique(inf_df$sample),
                    P_severe = P_severe_runs,
                    P_death = P_death_runs)

inf_df %<>% left_join( tmp_df, by = "sample")

inf_df= unique(inf_df)

inf_df %<>% mutate(Cases = inf_df$Infections * inf_df$P_severe)
inf_df %<>% mutate(Deaths = inf_df$Cases * inf_df$P_death)

rm(P_severe_runs, P_death_runs, n_samples)

```


```{r deaths_scenario_country2, fig.height=12, fig.width=10, fig.cap="Deaths per country."}
ggplot( filter(inf_df, Year %in% c(2050, 2070) )) + 
  geom_density_ridges(scale = 1, 
                      alpha = 0.8,
                      aes(x = Deaths, y = adm0, fill = scenario)) + 
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  scale_alpha_manual(values = c(0.1,0.5))+
  theme_ridges()+
  xlab("Deaths") + 
  ylab("Country")+
  scale_y_discrete(expand = c(0.01, 0)) +
  facet_wrap(Year~., nrow = 1)+
  scale_x_log10()

```


```{r median_deaths_table, fig.cap="Deaths per year in each scenario"}

p <- c(0.025, 0.25, 0.5, 0.75, 0.975)

p_names <- map_chr(p, ~paste0(.x*100, "%"))

p_funs <- map(p, ~partial(quantile, probs = .x, na.rm = TRUE)) %>% 
  set_names(nm = p_names)


kableExtra::kable(inf_df %>% 
                    group_by( Year, scenario) %>% 
                    summarise_at(vars(Deaths), funs(!!!p_funs)) %>% 
                    filter(Year %in% c(2018, 2050, 2070)), 
                  caption = "Median deaths per year in each scenario")

```


```{r deaths_percap_calc}

pop_all = read.csv("population.csv", stringsAsFactors = FALSE)

pop_all %<>% filter(year %in% 2018:2070) %>% 
  group_by(country_code, year) %>% 
  summarise(total_pop = sum(value))

pop_all %<>% dplyr::rename(adm0 = country_code, Year = year) %>%
  mutate(Year = as.character(Year))

inf_df %<>% left_join( pop_all, by = c("adm0", "Year"))

rm(pop_all)
```




```{r deaths_percap_country2, fig.height=12, fig.width=10, fig.cap="Deaths per capita per country."}
ggplot( filter(inf_df, Year %in% c(2050, 2070) )) + 
  geom_density_ridges(scale = 1, 
                      alpha = 0.8,
                      aes(x = Deaths/total_pop, y = adm0, fill = scenario)) + 
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  scale_alpha_manual(values = c(0.1,0.5))+
  theme_ridges()+
  xlab("Deaths per capita") + 
  ylab("Country")+
  scale_y_discrete(expand = c(0.01, 0)) +
  geom_vline(xintercept = 0)+
  facet_wrap(Year~., nrow = 1)+
  scale_x_log10()+
  theme(text = element_text(size = 20))

```

```{r deaths_percap_table, fig.cap="Deaths per capita per year in each scenario"}

inf_df %<>% mutate(Deaths_percap = (inf_df$Deaths / inf_df$total_pop))

out_df = inf_df %>% 
  group_by( Year, scenario) %>% 
  summarise_at(vars(Deaths_percap), funs(!!!p_funs)) %>% 
  filter(Year %in% c( 2050, 2070))

write.csv(out_df, "table_of_median_deaths_per_cap.csv", row.names = FALSE)

kableExtra::kable(out_df, caption = "Deaths per capita per year in each scenario")

```


\FloatBarrier

## Relative deaths per scenario

```{r relative_deaths_calc}

tmp = inf_df %>% filter( scenario == "now")
tmp %<>% dplyr::rename(Deaths_now = Deaths) %>% select("adm0", "Year", "Deaths_now", "sample")

inf_df %<>% left_join( tmp, by = c("adm0", "Year", "sample"))

rm(tmp)

inf_df %<>% mutate(relative_deaths = 100* (Deaths - Deaths_now)/ Deaths_now  ) 

inf_df %<>% unique()

inf_df %<>% mutate(death_diff = Deaths - Deaths_now ) 

inf_df %<>% unique()

```



```{r deaths_per_scenario_table}

out_df = inf_df %>% 
  group_by( Year, scenario, sample) %>% 
  summarise(sum_deaths = sum(Deaths)) %>% 
  filter(Year %in% c( 2050, 2070)) %>%
  group_by(Year, scenario) %>% 
  summarise_at(vars(sum_deaths), funs(!!!p_funs))

write.csv(out_df, "table_of_deaths.csv", row.names = FALSE)

kableExtra::kable(out_df, caption = "Deaths per year in each scenario")
```

```{r percentage_change_deaths_per_scenario_table}


out_df = inf_df %>% 
  group_by( Year, scenario) %>% 
  summarise_at(vars(relative_deaths), funs(!!!p_funs)) %>% 
  filter(Year %in% c( 2050, 2070))

write.csv(out_df, "table_of_median_percent_change_deaths.csv", row.names = FALSE)

kableExtra::kable(out_df, caption = "Median percentage change in deaths per year in each scenario")
```

```{r diff_deaths_per_scenario_table}


out_df = inf_df %>% 
  group_by( Year, scenario) %>% 
  summarise_at(vars(death_diff), funs(!!!p_funs)) %>% 
  filter(Year %in% c( 2050, 2070))

write.csv(out_df, "table_of_median_change_deaths.csv", row.names = FALSE)

kableExtra::kable(out_df, caption = "Median change in deaths per year in each scenario")
```



\FloatBarrier

## Deaths by region

```{r region_calc}


west = c("BEN", "BFA", "GMB", "GHA", "GIN", "GNB", "CIV", "LBR", "MLI", "MRT", "NER", "NGA", "SEN", "SLE", "TGO")

central = c("TCD", "CAF", "CMR", "GAB", "COD", "COG", "AGO", "SSD", "SDN")

inf_df %<>% mutate(WE = ifelse(adm0 %in% west, "West", 
                               ifelse(adm0 %in% central, "Central and Sudan",
                                      "East")))

```



```{r deaths_by_region}

ggplot(inf_df, aes(x = Year, y = Deaths, fill = scenario)) + 
  geom_violin( position="dodge", draw_quantiles = 0.5) +
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("Deaths")+
  facet_wrap(~WE) +
  scale_y_log10()


```


```{r deaths_percap_by_region2, fig.width=10, fig.height=8}


ggplot( filter(inf_df, scenario != "now")) + 
  geom_density_ridges(scale = 0.9, 
                      aes(x = Deaths_percap, y = WE, fill = scenario, alpha = Year)) + 
  facet_wrap(~scenario) +
  scale_fill_manual(values = c(snapalette(snapal)[1:4], "white"))+
  scale_alpha_manual(values = c(0.1,0.5, 0.8))+
  theme_ridges()+
  xlab("Deaths per capita") + 
  ylab("")+
  scale_x_log10()+
  scale_y_discrete(expand = c(0.01, 0))+
  guides(fill = FALSE)


```

# Proportion increasing

```{r increasing_calc}

fun_positive = function(vec, ind){
  vec = vec[ind]
  length(vec[vec>0])/length(vec)
}


propn_pos = NULL


scen_vec = c(26, 45, 60, 85)

for(s in 1:4){
  for(y in c(2050, 2070)){

    tmp = filter(inf_df, scenario == scen_vec[s] & Year == y)$relative_deaths

    boot_out = boot(tmp, fun_positive, 1000)
    
    bout_ci_calc = quantile(boot_out$t, c(0.025, 0.5,0.975))

    tmp_df = data.frame(scenario = scen_vec[s],
                        year = y,
                        proportion_pos = bout_ci_calc[2],
                        proportion_pos_ci = paste0("[",bout_ci_calc[1], ", ", bout_ci_calc[3], "]"))
    
    propn_pos = bind_rows(propn_pos, tmp_df)
  }
}

write.csv(propn_pos, "table_of_proportion_of_change_in_deaths_positive.csv", row.names = FALSE)

kableExtra::kable(propn_pos, caption = "Proportion of death change that are positive per year in each scenario")

```